apiVersion: quota.openshift.io/v1
kind: ClusterResourceQuota
metadata:
  annotations:
    openshift.io/cluster-quota-tier: Large
  labels:
    cluster-quota-tier: Large
  name: '{project}-quota'
spec:
  quota:
    hard:
      pods: "40"
      secrets: "60"
      cpu: "12"
      memory: 50Gi
  selector:
    annotations: null
    labels: null