apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: project-igniter-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - endpoints
  - resourcequotas
  - limitranges
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - project.openshift.io
  resources:
  - projects
  - projectrequests
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - authorization.openshift.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - quota.openshift.io
  resources:
  - projects
  - clusterresourcequotas
  verbs:
  - list
- apiGroups:
  - quota.openshift.io
  resources:
  - projects
  - clusterresourcequotas
  verbs:
  - '*'
- apiGroups:
  - lbroudoux.github.io
  resources:
  - '*'
  verbs:
  - '*'
